### ISSUE TITLE
USER STORY: Browse through products

### ISSUE THREAD

**Issue by domsq** [domsq/tina-q-cards#1]
As a **site user** I can **browse through products** so that **I can decide what I may be interested in buying**

### Acceptance Criteria:
- User can navigate to a page which shows an overview of products available

### Tasks
- [x] Create required view for displaying products
- [x] Configure template for use with the products view
- [x] Update URLs as needed
