### ISSUE TITLE
USER STORY: Browse through products

### ISSUE THREAD

**Issue by domsq** [domsq/tina-q-cards#1]
As a **site user** I can **browse through products ** so that **I can decide what I may be interested in buying**

### Acceptance Criteria:
- User will see a page which shows an overview of products available

### Tasks
- [ ] Create required view for displaying products
- [ ] Configure template for use with the products view
- [ ] Update URLs as needed
