### ISSUE TITLE
USER STORY: Sort products 

### ISSUE THREAD

**Issue by domsq** [domsq/tina-q-cards#19]
As a **site user** I can **sort products on criteria such as category or price** so that **I have a method of ordering the products as I prefer**

### Acceptance Criteria:
- The user will be able to select sort options from the "Products" dropdown menu in the header
- The user will be able to select sort options when viewing the products page 

### Tasks
- [x] Configure required views as needed to allow this functionality
- [x] Update required templates as needed
- [x] Configure required JavaScript as needed
