### ISSUE TITLE
USER STORY: View product detail

### ISSUE THREAD

**Issue by domsq** [domsq/tina-q-cards#2]
As a **site user** I can **look at product details** so that **I can decide whether I would like to buy it**

### Acceptance Criteria:
- When the user is browsing through the products overview page, they can click on a product to view details about it 

### Tasks
- [x] Create view to show product detail
- [x] Configure template for use with view
- [x] Update URLs as needed
