### ISSUE TITLE
USER STORY: View product detail

### ISSUE THREAD

**Issue by domsq** [domsq/tina-q-cards#2]
As a **site user** I can **look at product details** so that **I can decide whether I would like to buy it**

### Acceptance Criteria:
- When the user is browsing through the products overview page, they can click on a product to view details about it 

### Tasks
- [ ] Create view to show product detail
- [ ] Configure template for use with view
- [ ] Update URLs as needed
