### ISSUE TITLE
USER STORY: View contents of shopping basket

### ISSUE THREAD

**Issue by domsq** [domsq/tina-q-cards#4]
As a **site user** I can **view the contents of my shopping basket** so that **I can make any adjustments to it**

### Acceptance Criteria:
- If user clicks on the "basket" icon in the header, this will take them to a view of their basket
- The user can then adjust item quantities or remove them from the basket

### Tasks
- [x] Create view to allow showing of basket 
- [x] Configure template for use with view
- [x] Update URLs accordingly
