### ISSUE TITLE
USER STORY: View profile

### ISSUE THREAD

**Issue by domsq** [domsq/tina-q-cards#9]
As a **site user** I can **view a profile for my user account** so that **I can see my order history and also make any adjustments to the details kept on record for me**

### Acceptance Criteria:
- The user will be able to click on the "Account" icon from the header and, provided they're logged in, see their profile page
- From the profile page, they'll be able to adjust certain details for their account

### Tasks
- [ ] Create view to enable displaying of profile information
- [ ] Configure template for use with the view
- [ ] Update URLs as needed
